version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: opencoder
    container_name: opencoder
    # command: /usr/src/app/node_modules/.bin/nodemon server.js
    # volumes:
    #   - ./backend/:/app
    #   - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
      
networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    # node_modules:
    web-root:
      driver: local