export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_USER = "CREATE_USER";
export const GET_USER = "GET_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const GET_QUESTION = "GET_QUESTION";
export const RETRIEVE_QUESTIONS = "RETRIEVE_QUESTIONS";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";

export const DISPLAY_OUTPUT = "DISPLAY_OUTPUT";
export const CODE_CHANGE  = "CODE_CHANGE";
export const PREVIOUS_INPUT = "PREVIOUS_INPUT";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const LANG_CHANGE = "LANG_CHANGE";

export const CREATE_EXAM = "CREATE_EXAM";
export const GET_EXAM = "GET_EXAM";
export const RETRIEVE_EXAMS = "RETRIEVE_EXAMS";
export const UPDATE_EXAM = "UPDATE_EXAM";
export const DELETE_EXAM = "DELETE_EXAM";

export const CREATE_MARKS = "CREATE_MARKS";
export const GET_MARKS = "GET_MARKS";
export const RETRIEVE_MARKS = "RETRIEVE_MARKS";
export const UPDATE_MARKS = "UPDATE_MARKS";
export const DELETE_MARKS = "DELETE_MARKS";
